version: '3'

services:
    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        hostname: rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin